"""InitialModelsV1

Revision ID: ca7cbebbd277
Revises: ce30c5a6aecd
Create Date: 2024-07-19 21:45:31.110357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7cbebbd277'
down_revision: Union[str, None] = 'ce30c5a6aecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
