"""InitialModels

Revision ID: ce30c5a6aecd
Revises: 
Create Date: 2024-07-19 15:23:04.186567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce30c5a6aecd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.Enum('VW', 'SEAT', name='carbrand'), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year_of_release', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('engine_capacity', sa.Float(), nullable=False),
    sa.Column('gearbox', sa.Enum('MANUAL', 'AUTOMATIC', name='gearboxtype'), nullable=False),
    sa.Column('type_car', sa.Enum('SEDAN', 'LIFTBACK', 'HATCHBACK', name='cartype'), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('car_config', sa.Enum('BASIC', 'COMFORT', 'SPORT', 'PREMIUM', name='configcar'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
